### ISSUE TITLE
myqlm version conflict

### ISSUE THREAD

**Issue by Maximilien-B** [myQLM/qscore#1]
Seems Like there is a conflict issue whenever i try to install the package (i have tried on multiple distributions and virtual envirenoments but none seems to work and i get the same error each time)

<img width="1010" alt="image" src="https://github.com/myQLM/qscore/assets/30249881/e4f530ff-33b2-4f67-aee0-a1fc62bcde24">

Am i doing something wrong? If yes, would you mind telling me what it is ?

Thanks in advance,

Max

**Comment by ArnaudAtos** [comment]
Dear @MaxB0zz ,
Which version of Python and which plateform (e.g. Linux, MacOS) do you use?

**Comment by Maximilien-B** [comment]
Good day, 
i have tried on Ubuntu, Windows and Wsl2 with python 3.8.10 and 3.11.1. Same result on each of these versions.

**Comment by ArnaudAtos** [comment]
Good morning,
Unfortunatly, myQLM is not supported on Python 3.11 - your error message is expected for this version of Python. Supported version of Python is listed in [myQLM documentation](https://myqlm.github.io/myqlm_specific/install.html#compatibility-matrix)

Nevertheless, Python 3.8 is supported for both Windows and Ubuntu. Are you using _x84_64_ computer?
